services:
  - name: my-web-service
    type: web # Can be web, worker, cron, etc.
    env: node # Environment, such as node, python, ruby, etc.
    plan: standard # Plan type (e.g., free, standard)
    buildCommand: npm install && npm run build # Command to build the app
    startCommand: npm start # Command to start the app
    routes: # Routing rules for the service
      - type: rewrite
        source: '/*'
        destination: '/index.html'
    autoDeploy: true # Auto-deploy on git push
